"""添加图片相关表

Revision ID: a5df374d36a8
Revises: 2c2d09571075
Create Date: 2020-06-27 12:31:04.071861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5df374d36a8'
down_revision = '2c2d09571075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_ImageUrlInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=3000), nullable=True),
    sa.Column('object_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_ImageUrlInfo')
    # ### end Alembic commands ###
